name: CI - Build and Test

# Trigger on push to any branch, but exclude pull requests
on:
  push:
    branches:
      - '**'  # Run on all branches
  # Explicitly exclude pull_request events since we only want branch commits
  # pull_request: <-- commented out to exclude

# Set permissions for the workflow
permissions:
  contents: read

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]  # Use Node.js 20.x (LTS)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linter
        run: npm run lint
        
      - name: Run type checking
        run: npm run type-check
        
      - name: Run tests
        run: npm run test:run
        
      - name: Run build
        run: npm run build
        
      - name: Upload build artifacts (optional)
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: build-artifacts-node-${{ matrix.node-version }}
          path: dist/
          retention-days: 7
          
  # Optional: Add a job summary
  summary:
    name: Summary
    runs-on: ubuntu-latest
    needs: build-and-test
    if: always()
    
    steps:
      - name: Job Summary
        run: |
          echo "## CI Pipeline Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Build and Test Status" >> $GITHUB_STEP_SUMMARY
          if [ "${{ needs.build-and-test.result }}" == "success" ]; then
            echo "✅ **Build and Test**: Passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "❌ **Build and Test**: Failed" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Branch**: \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Commit**: \`${{ github.sha }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY