name: Deploy Preview

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ development ]
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: preview
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    concurrency:
      group: preview-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run type check
        run: npm run type-check
        
      - name: Run linting
        run: npm run lint
        
      - name: Run tests
        run: npm run test:run
        
      - name: Build project
        run: npm run build
        
      - name: Deploy to Vercel Preview
        uses: amondnet/vercel-action@v25
        id: vercel-deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./
          
      - name: Comment PR with preview URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo, number } = context.issue;
            const previewUrl = '${{ steps.vercel-deploy.outputs.preview-url }}';
            
            await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: `🚀 **Preview deployment ready!**\n\n**Preview URL:** ${previewUrl}\n\nDeployed from commit: ${context.sha.substring(0, 7)}`
            });